### ISSUE TITLE
package in source

### ISSUE THREAD

**Issue by igalic** [adamstrawson/puppet-byobu#2]
The package build is committed to the source tree.

That's generally not recommended, and instead you should create tags, and add `pkg` to `.gitignore`.

**Comment by adamstrawson** [comment]
Thanks @igalic I've removed them with your Pull Request, and will add a tag later on.

**Comment by igalic** [comment]
You're welcome, should probably also add  a new tag for the new version (I bumped the version in the Modulefile, when changing ensure's default)
